version: '3'

services:
  solr_node_1:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_1
    ports:
      - "127.0.0.1:8981:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_ZK_CREDS_AND_ACLS=${SOLR_ZK_CREDS_AND_ACLS}
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr_node_2:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_2
    ports:
      - "127.0.0.1:8982:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_ZK_CREDS_AND_ACLS=${SOLR_ZK_CREDS_AND_ACLS}
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr_node_3:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_3
    ports:
      - "127.0.0.1:8983:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_ZK_CREDS_AND_ACLS=${SOLR_ZK_CREDS_AND_ACLS}
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr_node_4:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_4
    ports:
      - "127.0.0.1:8983:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - SOLR_ZK_CREDS_AND_ACLS=${SOLR_ZK_CREDS_AND_ACLS}
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  zoo1:
    image: zookeeper
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 127.0.0.1:2181:2181
      - 127.0.0.1:7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  zoo2:
    image: zookeeper
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 127.0.0.1:2182:2181
      - 127.0.0.1:7002:7000
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  zoo3:
    image: zookeeper
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 127.0.0.1:2183:2181
      - 127.0.0.1:7003:7000
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr
      
networks:
  solr:

volumes:
  storage_solr_node_1:
  storage_solr_node_2:
  storage_solr_node_3:
  storage_solr_node_4:
