version: '3'

services:
  solr_node_1:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_1
    ports:
      - "8981:8983"
    environment:
      ZK_HOST: ${ZK_HOST}
      ZK_DIGEST_USERNAME: ${ZK_DIGEST_USERNAME}
      ZK_DIGEST_PASSWORD: ${ZK_DIGEST_PASSWORD}
      ZK_DIGEST_READONLY_USERNAME: ${ZK_DIGEST_READONLY_USERNAME}
      ZK_DIGEST_READONLY_PASSWORD: ${ZK_DIGEST_READONLY_PASSWORD}
      SOLR_HEAP: "8g"
    networks:
      - solr
    volumes:
      - storage_solr_node_1:/var/solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr_node_2:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_2
    ports:
      - "8982:8983"
    environment:
      ZK_HOST: ${ZK_HOST}
      ZK_DIGEST_USERNAME: ${ZK_DIGEST_USERNAME}
      ZK_DIGEST_PASSWORD: ${ZK_DIGEST_PASSWORD}
      ZK_DIGEST_READONLY_USERNAME: ${ZK_DIGEST_READONLY_USERNAME}
      ZK_DIGEST_READONLY_PASSWORD: ${ZK_DIGEST_READONLY_PASSWORD}
      
      SOLR_HEAP: "8g"
    networks:
      - solr
    volumes:
      - storage_solr_node_2:/var/solr    
    depends_on:
      - zoo1
      - zoo2
      - zoo3


  solr_node_3:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_3
    ports:
      - "8983:8983"
    environment:
      ZK_HOST: ${ZK_HOST}
      ZK_DIGEST_USERNAME: ${ZK_DIGEST_USERNAME}
      ZK_DIGEST_PASSWORD: ${ZK_DIGEST_PASSWORD}
      ZK_DIGEST_READONLY_USERNAME: ${ZK_DIGEST_READONLY_USERNAME}
      ZK_DIGEST_READONLY_PASSWORD: ${ZK_DIGEST_READONLY_PASSWORD}
      SOLR_HEAP: "8g"
    networks:
      - solr
    volumes:
      - storage_solr_node_3:/var/solr    
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr_node_4:
    image: ghcr.io/andreunix/solr:latest
    container_name: solr_node_4
    ports:
      - "8984:8983"
    environment:
      ZK_HOST: ${ZK_HOST}
      ZK_DIGEST_USERNAME: ${ZK_DIGEST_USERNAME}
      ZK_DIGEST_PASSWORD: ${ZK_DIGEST_PASSWORD}
      ZK_DIGEST_READONLY_USERNAME: ${ZK_DIGEST_READONLY_USERNAME}
      ZK_DIGEST_READONLY_PASSWORD: ${ZK_DIGEST_READONLY_PASSWORD}
      SOLR_HEAP: "8g"
    networks:
      - solr    
    volumes:
      - storage_solr_node_4:/var/solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3



  zoo1:
    image: zookeeper
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: ${ZOO_SERVERS}
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  zoo2:
    image: zookeeper
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
      - 7002:7000
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: ${ZOO_SERVERS}
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  zoo3:
    image: zookeeper
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 127.0.0.1:2183:2181
      - 127.0.0.1:7003:7000
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: ${ZOO_SERVERS}
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr
      
networks:
  solr:

volumes:
  storage_solr_node_1:
  storage_solr_node_2:
  storage_solr_node_3:
  storage_solr_node_4:
