version: '3.9'

services:
  database:
    image: mariadb:11.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: development
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
    ports:
      - "3306:3306"
